version: "3"

services:
  redis:
    image: redis:alpine
  bot:
    image: node:8
    links:
      - redis:redis
    environment:
      DRY_RUN: 1
      DB: redis
      REDIS_URL: redis://redis
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start